### ISSUE TITLE
Citing the denoiser and contributors?

### ISSUE THREAD

**Issue by NatashaLTaylor** [arielletambini/denoiser#31]
I have recently used this great tool to perform denoising on some functional data. I was wondering if you have a preferred or recommended method of acknowledging your contributions and citing the denoiser? 

Thanks,
Natasha

**Comment by arielletambini** [comment]
Hi Natasha,

This is great to hear that the tool was useful for you! We just made a doi for it so it is now citable. You can use this as the citation: 

Tambini, Arielle, & Gorgolewski, Krzysztof J. (2020, September 17). Denoiser: A nuisance regression tool for fMRI BOLD data (Version 1.0.0). Zenodo. http://doi.org/10.5281/zenodo.4033785

full info here: https://zenodo.org/record/4033785#.X2LoUGdKjfZ

Thanks for bringing this up!
Best,
Arielle

**Comment by NatashaLTaylor** [comment]
Hi Arielle,

Thank you for putting the citation together! 
Greatly appreciated, and a really useful tool that you have built. 

Kind regards,
Natasha
